# -*- coding: utf-8 -*-
"""Auto-generated by geocode_institutions.py. INSTITUTION study coords.
Resolve a raw sheet token with: COORDS.get(ALIASES.get(tok, tok)).
"""

INSTITUTION_ALIASES = {
    'Brain Mind Institute': 'EPFL',
    "Children's Hospital of Philadelphia": 'Children’s Hospital of Philadelphia',
    'Concordia': 'Concordia University',
    'Cornell': 'Cornell University',
    'Department of Earth and Environmental Sciences': '',
    'Donders Institute for Brain': 'Donders Institute',
    'Inc': '',
    'Jaume I University': 'Universitat Jaume I',
    'KU': 'KU Leuven',
    'Laboratory of Synaptic Mechanisms': 'EPFL',
    'Max Planck': 'Max Planck Institute of Psychiatry',
    'McGill': 'McGill University',
    'NIDA': 'National Institute on Drug Abuse',
    'NIH': 'National Institutes of Health',
    'NIHM': 'National Institute of Mental Health',
    'NYU': 'New York University',
    'National Autonomous University of Mexico': 'UNAM',
    'Polish Academy of Science': 'Polish Academy of Sciences',
    'Pontificia UniversidadCatólica del Ecuador': 'Pontificia Universidad Católica del Ecuador',
    'RCSI': 'Royal College of Surgeons in Ireland',
    'Salk': 'Salk Institute for Biological Studies',
    'St. Louis': 'Washington University in St. Louis',
    'Stanford': 'Stanford University',
    'Technical University Darmstadt': 'Technische Universität Darmstadt',
    'Texas A&M': 'Texas A&M University',
    "The Children's Hospital of Philadelphia Research Institute": 'Children’s Hospital of Philadelphia',
    'The University of Hong Kong': 'University of Hong Kong',
    'University': '',
    'University Darmstadt': 'Technische Universität Darmstadt',
    'University of Bordeaux': 'Université de Bordeaux',
    'University of California': 'University of California San Diego',
    'University of California San Diego.': 'University of California San Diego',
    'University of Leuven': 'KU Leuven',
    'University of New South Wales': 'UNSW Sydney',
    'University ofWashington': 'University of Washington',
    'Washington University': 'Washington University in St. Louis',
    'Zhengzhou': '',
    'etherlands Institute for Neuroscience': 'Netherlands Institute for Neuroscience',
    'niversity of Pennsylvania': 'University of Pennsylvania',
    'École Polytechnique Fédérale de Lausanne': 'EPFL',
}

INSTITUTION_COORDS = {
    'Amherst College': [42.3704, -72.5161],  # 1
    'Aquatic Technology Promotion Station of Xiangshan County': [29.4776, 121.8695],  # 1
    'Arctic University of Norway': [69.6819, 18.9725],  # 1
    'BROAD Institute': [42.3626, -71.0866],  # 1
    'Biobizkaia Health Research Institute': [43.2983, -2.9903],  # 2
    'Boehringer Ingelheim Pharma GmbH & Co.': [49.9764, 8.0917],  # 1
    'Boston University Medical Center': [42.336, -71.0723],  # 1
    'CIBERsam-ISCiii': [40.5088, -3.6903],  # 1
    'CaaMTech': [47.5301, -122.0326],  # 1
    'Cadi Ayyad University': [31.6661, -8.0005],  # 2
    'Canadian Institute for Advanced Research (CIFAR)': [43.6532, -79.3832],  # 1
    'Carnegie Mellon University': [40.4439, -79.9428],  # 1
    'Centros de Integración Juvenil': [19.36, -99.18],  # 1
    'Charles University': [50.0889, 14.4163],  # 1
    'Children’s Hospital of Philadelphia': [39.9477, -75.195],  # 3
    'Christian-Albrechts-Universität zu Kiel': [54.3458, 10.1131],  # 1
    'City University of Hong Kong': [22.34, 114.1697],  # 2
    'Columbia University': [40.8078, -73.9625],  # 2
    'Columbia University Irving Medical Center': [40.842, -73.9437],  # 2
    'Concordia University': [45.4583, -73.6394],  # 2
    'Cornell University': [42.4529, -76.4801],  # 3
    'DLH Corporation': [33.749, -84.388],  # 1
    'Dalhousie University': [44.6362, -63.592],  # 1
    'Deakin University': [-37.8475, 145.1149],  # 1
    'Donders Institute': [51.8199, 5.8637],  # 1
    'Duke University': [36.0002, -78.9442],  # 1
    'ELTE Eötvös Loránd University': [47.4935, 19.0619],  # 1
    'EMBL Rome': [42.0842, 12.5935],  # 4
    'EPFL': [46.5191, 6.5668],  # 4
    'Emory University': [33.8005, -84.3172],  # 1
    'Federal University of Paraíba': [-7.1386, -34.8452],  # 1
    'Florey Institute': [-37.7963, 144.9614],  # 1
    'Florida Atlantic University': [26.1194, -80.1417],  # 3
    'Fujita Health University': [35.0709, 137.0004],  # 1
    'George Washington University': [38.8999, -77.0474],  # 1
    'Georgetown University Medical Center': [38.9118, -77.0752],  # 2
    'Georgia State University': [33.7536, -84.3854],  # 1
    'Gifu University': [35.4644, 136.738],  # 1
    'HUN-REN Biological Research Centre': [46.2472, 20.1447],  # 1
    'Harvard Medical School': [42.3369, -71.1039],  # 4
    'Harvard Stem Cell Institute': [42.377, -71.1167],  # 1
    'Heidelberg University': [49.4186, 8.6692],  # 1
    'Hiroshima University': [34.4016, 132.7207],  # 1
    'Hospital General Dr. Manuel Gea González': [19.3007, -99.188],  # 1
    'Hospital for Sick Children': [43.6573, -79.3876],  # 1
    'Howard Hughes Medical Institute': [38.9985, -77.0796],  # 1
    'Humboldt University': [52.5178, 13.3936],  # 1
    'Hungarian Centre of Excellence for Molecular Medicine': [46.253, 20.1414],  # 1
    'IRCCS Humanitas Research Hospital': [45.3592, 9.1725],  # 1
    'Icahn School of Medicine': [40.7898, -73.9533],  # 1
    'Indian Institute of Technology Madras': [12.9942, 80.2367],  # 2
    'Inscopix': [37.4419, -122.143],  # 1
    'Institute of Physiology of the Czech Academy of Sciences': [50.0407, 14.474],  # 1
    'Instituto de Salud Carlos III': [40.476, -3.6939],  # 1
    'Johannes Gutenberg University': [49.992, 8.2371],  # 1
    'KU Leuven': [50.8779, 4.7005],  # 6
    'Karolinska Institutet': [59.3515, 18.0311],  # 3
    'Kindai University': [34.6517, 135.5913],  # 1
    'Kobe University': [34.6638, 135.0291],  # 1
    'Lehigh University': [40.6068, -75.3782],  # 4
    'Linköping University': [58.3978, 15.5755],  # 1
    'MCCI Corporation': [42.443, -76.5019],  # 1
    'Macquarie University': [-33.7742, 151.1127],  # 2
    'Mahidol University': [13.7947, 100.3219],  # 1
    'Massachusetts General Hospital': [42.3629, -71.0688],  # 1
    'Max Planck Institute of Psychiatry': [48.1497, 11.567],  # 4
    'McGill University': [45.5048, -73.5772],  # 2
    'McLean Hospital': [42.3933, -71.1902],  # 1
    'Medical College of Wisconsin': [43.0439, -88.0225],  # 2
    'Medical Research Council Harwell': [51.5745, -1.311],  # 1
    'Michigan State University': [42.7024, -84.4804],  # 2
    'Monash University': [-37.784, 144.9587],  # 1
    'Nagoya University': [35.1533, 136.9678],  # 1
    'Nanjing Medical University': [31.9858, 118.703],  # 1
    'Nanjing University of Chinese Medicine': [32.103, 118.9389],  # 1
    'National Institute of Diabetes and Digestive and Kidney Diseases': [39.0003, -77.1029],  # 1
    'National Institute of Mental Health': [39.0003, -77.1029],  # 3
    'National Institute on Deafness and other Communication Disorders': [39.0003, -77.1029],  # 1
    'National Institute on Drug Abuse': [39.2946, -76.5836],  # 5
    'National Institutes of Health': [39.0003, -77.1029],  # 3
    'National Research Council of Italy': [41.9033, 12.5147],  # 1
    'Nencki Institute of Experimental Biology of the Polish Academy of Sciences': [52.256, 21.03],  # 1
    'Netherlands Institute for Neuroscience': [52.3593, 4.9531],  # 1
    'Netholabs': [51.5074, -0.1278],  # 1
    'New York State Psychiatric Institute': [40.8425, -73.9446],  # 1
    'New York University': [40.7295, -73.9965],  # 4
    'Ningbo Institute of Oceanography': [29.8683, 121.544],  # 1
    'Ningbo University': [29.9092, 121.6335],  # 1
    'Northwestern University': [42.0557, -87.6753],  # 2
    'Northwestern University Feinberg School of Medicine': [41.8961, -87.6172],  # 2
    'Osaka University': [34.5112, 135.6314],  # 1
    'Peking University School of Life Sciences': [39.9925, 116.3058],  # 1
    'Penn State University': [40.8129, -77.8711],  # 1
    'Philipps-University Marburg': [50.8125, 8.7722],  # 1
    'Platea Biosciences': [42.2626, -71.8023],  # 3
    'Polish Academy of Sciences': [52.2378, 21.0182],  # 4
    'Pontificia Universidad Católica del Ecuador': [-0.21, -78.4917],  # 1
    'Qingdao University': [35.9817, 120.1623],  # 1
    'Roche': [47.558, 7.602],  # 1
    'Rosalind Franklin University': [42.3022, -87.8585],  # 1
    'Royal College of Surgeons in Ireland': [53.3392, -6.2626],  # 1
    'Royal Hospital for Women': [-33.9169, 151.238],  # 1
    'SMART Biomedical Microsystems Laborator Université de Sherbrooke': [45.3785, -71.9245],  # 1
    'Salk Institute for Biological Studies': [32.8872, -117.2454],  # 1
    'Shinshu University': [36.7116, 138.4936],  # 1
    'Southeast University': [31.8892, 118.8156],  # 1
    'Southern Illinois University-Carbondale': [37.7083, -89.2276],  # 1
    'Srinakharinwirot University': [13.7449, 100.5648],  # 1
    'Stanford University': [37.4313, -122.1694],  # 5
    "Sydney Children's Hospital Randwick": [-33.9177, 151.2384],  # 1
    'TU Dresden': [51.0283, 13.736],  # 1
    'Technische Universität Darmstadt': [49.8612, 8.6819],  # 2
    'Texas A&M University': [30.6109, -96.3521],  # 2
    'The International Brain Laboratory': [51.5246, -0.134],  # 1
    'The Second Affiliated Hospital of Nanjing Medical University': [32.0616, 118.7788],  # 1
    'UNAM': [19.332, -99.187],  # 2
    'UNSW Sydney': [-33.9173, 151.2313],  # 2
    'Universidade de Lisboa': [38.7528, -9.157],  # 2
    'Universitat Jaume I': [39.9943, -0.0714],  # 5
    'University College Cork': [51.8947, -8.4903],  # 2
    'University College London': [51.5242, -0.133],  # 1
    'University Miguel Hernández': [38.277, -0.6899],  # 1
    'University of Amsterdam': [52.3681, 4.8898],  # 3
    'University of Arizona': [32.2357, -110.9517],  # 1
    'University of Bonn': [50.7338, 7.1022],  # 1
    'University of British Columbia': [49.2579, -123.243],  # 1
    'University of Cagliari': [39.2238, 9.1217],  # 1
    'University of Calgary': [51.0751, -114.1388],  # 4
    'University of California San Diego': [32.8792, -117.2311],  # 3
    'University of Cambridge': [52.1891, 0.1213],  # 1
    'University of Geneva': [46.1952, 6.1408],  # 3
    'University of Haifa': [32.7609, 35.0205],  # 2
    'University of Hong Kong': [22.283, 114.1371],  # 5
    'University of Illinois at Chicago': [41.8676, -87.6524],  # 1
    'University of Massachusetts Dartmouth': [41.6225, -71.0073],  # 1
    'University of Melbourne': [-37.8241, 144.9171],  # 1
    'University of Milan': [45.4757, 9.2283],  # 1
    'University of Nebraska': [40.8206, -96.7056],  # 1
    'University of North Carolina': [35.9049, -79.0469],  # 5
    'University of Oxford': [51.7548, -1.2544],  # 1
    'University of Pennsylvania': [39.9522, -75.1956],  # 2
    'University of Pennsylvania School of Veterinary Medicine': [39.9509, -75.2],  # 1
    'University of Saskatchewan': [52.1344, -106.6278],  # 1
    'University of South Florida': [28.06, -82.4138],  # 1
    'University of South Florida Health': [28.0625, -82.4088],  # 1
    'University of Tennessee': [35.9516, -83.9309],  # 1
    'University of Texas': [30.2849, -97.7341],  # 1
    'University of Texas at Austin': [30.2851, -97.7339],  # 4
    'University of Toronto': [43.6608, -79.396],  # 2
    'University of Tsukuba': [36.1071, 140.1007],  # 1
    'University of Veterinary Medicine Vienna': [48.2548, 16.4304],  # 2
    'University of Warsaw': [52.2216, 21.0074],  # 1
    'University of Washington': [47.6553, -122.3035],  # 11
    'University of Wisconsin-Madison': [43.0803, -89.431],  # 1
    'University of the Basque Country': [43.3092, -2.0108],  # 3
    'Université Côte d’Azur': [43.717, 7.2676],  # 1
    'Université Laval': [46.7812, -71.2741],  # 1
    'Université de Bordeaux': [44.8097, -0.5974],  # 2
    'VA Boston': [42.2977, -71.1449],  # 1
    'Vanderbilt University': [36.1438, -86.8028],  # 1
    'Washington State University': [46.7338, -117.1498],  # 2
    'Washington University in St. Louis': [38.6488, -90.3108],  # 8
    'Wayne State University': [42.3572, -83.0709],  # 1
    'Weizmann Institute of Science': [31.9078, 34.8133],  # 3
    'Yale School of Medicine': [41.3352, -72.9187],  # 1
}
